version: "3.3"

services:
  spk-indexer-node: # name of the service
    build: .
    image: spk-indexer-node # the image to use
    container_name: spk-indexer-node # what to label the container for docker ps
    ports:
      - 4567:4567 # note, we're mapping to port 80 instead of 5000 because we'll use 80 on the VPS
    restart: always # restart if failed, until we stop it ourselves
    links:
      - mongo
    #external_links:
      #- mongo
    depends_on:
      - mongo
      - ipfs
    networks:
      - spk-indexer-network
    environment:
      MONGO_HOST: mongo:27017
      IPFS_HOST: ipfs:5001
      JAEGER_HOST: jaeger
      JAEGER_PORT: 6832
      ENABLE_CORS: "true"
  mongo:
    restart: always
    container_name: mongo
    image: mongo:5.0.9
    command: --replSet dbrs 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 'wMu$OHB0e86r'
    ports:
      - 127.0.0.1:27028:27017
    networks:
      - spk-indexer-network
    volumes:
      - ./data/mongodb:/data/db
      - ./deploy/replica.key:/data/db/mongodb.key
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:latest
    command:
      - daemon
      - --enable-pubsub-experiment
    networks:
      - spk-indexer-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6832:6832/udp"
      - "16686:16686"
    networks:
      - spk-indexer-network
networks:
  spk-indexer-network:
    driver: bridge
